### ISSUE TITLE
Images dont load, dont even creates the HTML code

### ISSUE THREAD

**Issue by tiagofcp** [aryehraber/statamic-responsive-img#14]
Hi.
Im trying to use ResponsiveIMG but im having a issue, i cant get to load the assets that are choose when we edit the page on the backoffice.
This is my responsive code
`{{ responsive_img:image_bundleitem }}`

I can load the image normally with the img tag
and if i place for example this on top of the template file

```
---
banner: /assets/services/destaquefatkiller.jpg
---

{{ responsive_img:banner }}
```

and if i use then this on the code it works

Can someone help me please

**Comment by tiagofcp** [comment]
If i do 
`{{ image_bundleitem | dump }}`
it shows the right url to the img

**Comment by simonhamp** [comment]
I've had similar issues since upgrading our site to Statamic 2.11.9.

A `php please clear:cache` usually sorts it out.

But it's weird that it happens somewhat sporadically.

**Comment by aryehraber** [comment]
Latest release should fix the above issue! 

Turns out at some point the Tag `__call()` method started receiving the camelcase version of method names, which didn't match up with the context's variable names (image variables). Eg: `my_hero_banner` would become `myHeroBanner`, however `banner` remained `banner` because it was a singular word.
